// Unique identifier
export type UUID = string;

// Timestamp in milliseconds
export type Timestamp = number;

/**
 * A saved tab/page
 */
export interface SavedItem {
  id: UUID;
  url: string;
  title: string;
  favicon: string;              // Base64 or URL fallback
  faviconType: 'base64' | 'url';
  savedAt: Timestamp;
  lastAccessedAt: Timestamp;    // For sorting by recent access
  
  // Captured context
  referrerQuery: string | null; // Search query that led to this page
  referrerUrl: string | null;   // The actual referrer URL
  siblingTabUrls: string[];     // Other tabs open when saved
  
  // Categorization (multi-select)
  topicIds: UUID[];
  intentIds: UUID[];
  
  // For search
  searchText: string;           // Lowercase concat of title + url + referrerQuery
}

/**
 * Topic category (auto-generated or user-created)
 */
export interface Topic {
  id: UUID;
  name: string;
  color: string;                // Hex color
  isAutoGenerated: boolean;
  createdAt: Timestamp;
  itemCount: number;            // Denormalized for sidebar display
}

/**
 * Intent category (user-selected)
 */
export interface Intent {
  id: UUID;
  name: string;
  emoji: string;
  createdAt: Timestamp;
  itemCount: number;
}

/**
 * Custom quick link
 */
export interface CustomLink {
  id: UUID;
  name: string;
  url: string;
  icon?: string; // Optional icon identifier or emoji
}

/**
 * User settings
 */
export interface Settings {
  id: string;                   // Always 'main'
  keyboardShortcut: string;     // Default: "Cmd+Shift+S"
  autoSaveDelay: number;        // Default: 5000 (ms)
  showResurfaceDropdown: boolean;
  defaultIntentId: UUID | null;
  // New tab settings
  newTabShowLogo: boolean;        // Default: true
  newTabEnabledShortcuts: string[]; // Array of shortcut IDs (e.g., ['gmail', 'drive', 'youtube'])
  newTabCustomLinks: CustomLink[];  // User-added custom links
}

/**
 * Page data extracted by content script
 */
export interface PageData {
  url: string;
  title: string;
  favicon: string;
  faviconType: 'base64' | 'url';
  referrerUrl: string | null;
  referrerQuery: string | null;
}

/**
 * Data passed to toast for display
 */
export interface ToastData {
  pageData: PageData;
  suggestedTopics: Topic[];
  intents: Intent[];
  siblingTabUrls: string[];
  autoSaveDelay: number;
}

/**
 * User's selections from the toast
 */
export interface ToastResult {
  title: string;
  topicIds: UUID[];
  intentIds: UUID[];
}

/**
 * Item formatted for dropdown display
 */
export interface DropdownItem {
  id: UUID;
  title: string;
  url: string;
  favicon: string;
  faviconType: 'base64' | 'url';
  domain: string;
  savedAt: string;      // Formatted relative time
  topics: Topic[];
  intents: Intent[];
}
